# Generated by Django 5.0 on 2023-12-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.TextField()),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('read', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
