# Generated by Django 4.2.7 on 2023-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='nationality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
