# Generated by Django 4.2.7 on 2023-12-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyresponse_nationality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='nationality',
            new_name='country_of_birth',
        ),
    ]
